version: '3.8'

services:
  app:
    build: .
    container_name: crud_visiteurs_app
    ports:
      - "8000:80" # Redirige le port 80 du conteneur vers le port 8000 de votre machine locale
    volumes:
      - .:/var/www/html # Lie votre code source Laravel au conteneur
    depends_on:
      - db # Indique que l'application dépend du service MySQL
    networks:
      - crud_visiteurs_network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=crud-visiteurs
      - DB_USERNAME=root
      - DB_PASSWORD=
    command: /bin/bash -c "/usr/local/bin/wait-for-it.sh db:3306 -- php artisan serve --host=0.0.0.0"

  db:
    image: mysql:5.7
    container_name: crud_visiteurs_db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: crud-visiteurs
      MYSQL_USER: user
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - crud_visiteurs_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  crud_visiteurs_network:
    driver: bridge

volumes:
  mysql_data:
